//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Role
    {
        public Auth_Role()
        {
            this.Auth_Access = new HashSet<Auth_Access>();
            this.Auth_UserRole = new HashSet<Auth_UserRole>();
        }
    
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public int RoleType { get; set; }
        public bool IsAvaiable { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<Auth_Access> Auth_Access { get; set; }
        public virtual ICollection<Auth_UserRole> Auth_UserRole { get; set; }
    }
}
