//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Permission
    {
        public Auth_Permission()
        {
            this.Auth_Access = new HashSet<Auth_Access>();
        }
    
        public string PermissionId { get; set; }
        public string ParentId { get; set; }
        public string PermissionNo { get; set; }
        public string PermissionName { get; set; }
        public int PermissionType { get; set; }
        public string ResourceUrl { get; set; }
        public string Target { get; set; }
        public int SortIndex { get; set; }
        public bool IsVisible { get; set; }
        public bool IsAvaiable { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UPdateDate { get; set; }
    
        public virtual ICollection<Auth_Access> Auth_Access { get; set; }
    }
}
