//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserAccounts = new HashSet<UserAccount>();
            this.UserThirdAccounts = new HashSet<UserThirdAccount>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
        public virtual ICollection<UserThirdAccount> UserThirdAccounts { get; set; }
    }
}
